-- Adicionando um imóvel de exemplo para o usuário imobitec
-- Incluindo todos os campos necessários para evitar erros no frontend
INSERT INTO products (
  user_id, 
  name, 
  image, 
  description, 
  price, 
  niche, 
  property_type, 
  bedrooms, 
  bathrooms, 
  suites, 
  parking_spaces, 
  area, 
  location, 
  is_for_sale, 
  is_for_rent, 
  condo_fee, 
  iptu, 
  map_url,
  video_url,
  images, 
  optionals,
  colors,
  is_active
) VALUES (
  'b10ee75a-394f-4e9b-9401-8562b69aa59b',
  'Apartamento de Luxo com Vista para o Mar',
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
  'Este espetacular apartamento de luxo oferece uma experiência de vida inigualável. Com acabamentos de altíssimo padrão, amplas janelas do chão ao teto e uma varanda gourmet espaçosa, este imóvel é perfeito para quem busca conforto e exclusividade. Localizado no coração do bairro mais prestigiado, próximo a shoppings, restaurantes de alta gastronomia e com fácil acesso às principais avenidas.',
  1250000.00,
  'realestate',
  'Apartamento',
  3,
  4,
  2,
  2,
  145,
  'Ponta Negra, Manaus',
  true,
  false,
  850.00,
  1200.00,
  'https://maps.app.goo.gl/yQYvAnGfX5nZ9m5v7',
  'https://www.youtube.com/watch?v=ScMzIvxBSi4',
  '["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800"]',
  '["Piscina", "Churrasqueira", "Academia", "Salão de Festas", "Portaria 24h", "Varanda Gourmet", "Mobiliado", "Vista para o Mar"]',
  '["#000000"]',
  true
);
