-- 1. ADICIONAR COLUNA DE DESCONTO NA TABELA PLANS
ALTER TABLE plans ADD COLUMN IF NOT EXISTS discount INT DEFAULT 0;

-- 2. GARANTIR QUE OS PLANOS EXISTENTES TENHAM 0 DE DESCONTO
UPDATE plans SET discount = 0 WHERE discount IS NULL;

-- 3. RECARREGAR O SCHEMA PARA A VERCEL ENXERGAR A COLUNA NOVA
NOTIFY pgrst, 'reload schema';
