-- ADICIONAR COLUNAS PARA CONSÓRCIO E FINANCIAMENTO NA TABELA PRODUCTS
ALTER TABLE products ADD COLUMN IF NOT EXISTS consortium_image TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS liberacred_image TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS has_liberacred BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS has_consortium BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS show_consortium_plans BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS consortium_plans TEXT DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS show_financing_plans BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS financing_plans TEXT DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS cash_price TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS card_installments TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS card_interest BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS property_status TEXT DEFAULT 'ready';

-- RECARREGAR O SCHEMA PARA O POSTGREST (REQUISITO DA VERCEL/SUPABASE)
NOTIFY pgrst, 'reload schema';
