-- 1. ADICIONAR COLUNAS FALTANTES NA TABELA PLANS
ALTER TABLE plans ADD COLUMN IF NOT EXISTS discount INT DEFAULT 0;
ALTER TABLE plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. GARANTIR QUE OS PLANOS EXISTENTES ESTEJAM COM DADOS VÁLIDOS
UPDATE plans SET discount = 0 WHERE discount IS NULL;
UPDATE plans SET updated_at = NOW() WHERE updated_at IS NULL;

-- 3. RECARREGAR O SCHEMA PARA A VERCEL ENXERGAR AS COLUNAS NOVAS
NOTIFY pgrst, 'reload schema';
