-- SQL Scripts for Supabase SQL Editor

-- 1. Create Profiles table (extension of auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  role_title TEXT,
  profile_image TEXT,
  whatsapp TEXT,
  instagram TEXT,
  facebook TEXT,
  slug TEXT UNIQUE NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  admin_message TEXT,
  admin_message_date TIMESTAMP WITH TIME ZONE,
  plan_type TEXT DEFAULT 'Standard',
  expiry_date DATE,
  email TEXT,
  status TEXT DEFAULT 'active',
  establishment TEXT,
  documento TEXT,
  niche TEXT DEFAULT 'vehicle',
  card_bottom_image TEXT,
  card_background_image TEXT,
  profile_banner_image TEXT,
  marquee_text TEXT,
  marquee_speed INTEGER DEFAULT 20,
  show_marquee BOOLEAN DEFAULT TRUE,
  show_catalog_banner BOOLEAN DEFAULT FALSE,
  show_profile_banner BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now()) NOT NULL
);

-- 2. Create Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  image TEXT,
  description TEXT,
  colors JSONB,
  images JSONB,
  threeSixtyImages JSONB,
  consortiumPlanImage TEXT,
  liberacredImage TEXT,
  hasLiberacred BOOLEAN DEFAULT FALSE,
  year INTEGER,
  price NUMERIC,
  mileage NUMERIC,
  brand TEXT,
  condition TEXT,
  fuel TEXT,
  transmission TEXT,
  color TEXT,
  optionals JSONB,
  is_highlighted BOOLEAN DEFAULT FALSE,
  is_new BOOLEAN DEFAULT TRUE,
  has_consortium BOOLEAN DEFAULT TRUE,
  show_consortium_plans BOOLEAN DEFAULT FALSE,
  consortium_plans JSONB,
  show_financing_plans BOOLEAN DEFAULT FALSE,
  financing_plans JSONB,
  cash_price NUMERIC,
  card_installments TEXT,
  card_interest BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  niche TEXT DEFAULT 'vehicle',
  property_type TEXT,
  bedrooms INTEGER,
  bathrooms INTEGER,
  suites INTEGER,
  parking_spaces INTEGER,
  area NUMERIC,
  location TEXT,
  is_for_sale BOOLEAN DEFAULT TRUE,
  is_for_rent BOOLEAN DEFAULT FALSE,
  condo_fee NUMERIC,
  iptu NUMERIC,
  video_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT (now()) NOT NULL
);

-- 3. Create System Settings table
CREATE TABLE system_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  default_logo TEXT,
  default_phone TEXT,
  footer_logo TEXT,
  favicon TEXT,
  footer_text TEXT,
  system_version TEXT DEFAULT 'V2.0.4',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now()) NOT NULL
);

-- 4. Initial default row
INSERT INTO system_settings (id, default_logo, default_phone, footer_logo, favicon, footer_text) 
VALUES (1, null, null, null, null, '© 2026 Smart Cartão - Todos os direitos reservados.') 
ON CONFLICT (id) DO NOTHING;

-- 5. Set up Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Profiles viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can edit own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Products Policies
CREATE POLICY "Products viewable by everyone" ON products FOR SELECT USING (true);
CREATE POLICY "Users can manage own products" ON products FOR ALL USING (auth.uid() = user_id);

-- System Settings Policies
CREATE POLICY "Settings viewable by everyone" ON system_settings FOR SELECT USING (true);
CREATE POLICY "Only admins can edit settings" ON system_settings FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Adicionar novas colunas para mockups da Landing Page
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS landing_mockup_service TEXT;
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS landing_mockup_features TEXT;
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS landing_mockup_hero TEXT;

ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS landing_faqs TEXT;
