export interface Product {
  id: string | number;
  name: string;
  image: string;
  description: string;
  colors: string[];
  consortiumPlanImage?: string;
  liberacredImage?: string;
  financingInfo?: string;
  hasLiberacred?: boolean;
  images?: string[];
  threeSixtyImages?: string[];
  year?: number;
  price?: string | number;
  mileage?: string | number;
  brand?: string;
  condition?: string;
  fuel?: string;
  transmission?: string;
  color?: string;
  optionals?: string[];
  is_highlighted?: boolean;
  is_new?: boolean;
  has_consortium?: boolean;
  show_consortium_plans?: boolean;
  consortium_plans?: { installments: number; value: string }[];
  show_financing_plans?: boolean;
  financing_plans?: { down_payment: string; installments: number; value: string }[];
  cash_price?: string;
  card_installments?: string;
  card_interest?: boolean;
  is_active?: boolean;
  niche?: 'vehicle' | 'realestate';
  property_type?: string;
  bedrooms?: number | string;
  bathrooms?: number | string;
  suites?: number | string;
  parking_spaces?: number | string;
  area?: number | string;
  location?: string;
  is_for_sale?: boolean;
  is_for_rent?: boolean;
  condo_fee?: string | number;
  iptu?: string | number;
  map_url?: string;
  video_url?: string;
}

export interface FinancingFormData {
  nome: string;
  cidade: string;
  nascimento: string;
  cpf: string;
  telefone: string;
  modelo: string;
  modelo_id?: string | number;
  entrada: string;
  status: 'assalariado' | 'autonomo';
  cnh: 'sim' | 'nao';
  renda: string;
  cep: string;
  endereco: string;
  bairro: string;
  cor: string;
}
